In [1]:
import pandas as pd
import glob
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
import sqlite3

# Phân tích chi phí tăng giảm trong tỉnh

In [2]:
# Dữ liệu tại năm hiện tại cần phân tích
con = sqlite3.connect(r'D:\DATACSDL\CSDL\2021\93_20210912_202101_202108_bao_cao_bhyt7980a.db')

In [3]:
#frame.select_dtypes(include='int64')
#frame.isna().sum()
#frame.describe()
#table = pd.pivot_table(frame,index=['MA_CSKCB'],columns=['THANG_QT'],values=['T_BHTT'],aggfunc=['sum'])
#tablecount = frame_noitru[["MA_CSKCB","THANG_QT"]].copy()

In [4]:
CHIPHITAICSKCB = (r'SELECT MA_CSKCB,MA_LOAI_KCB,COUNT(MA_THE) AS "SO_LUOT",ROUND(SUM(T_TONGCHI),0) AS "TONGCHI",'
                + ' ROUND(SUM(T_KHAM),0) AS "T_KHAM",ROUND(SUM(T_TTPT),0) as "T_TTPT",ROUND(SUM(T_THUOC),0) as "T_THUOC",'
                + ' ROUND(SUM(T_TONGCHI),0) / COUNT(MA_THE) as "CPBQ_KCB",'
                + ' ROUND(SUM(T_TTPT),0) / ROUND(SUM(T_TONGCHI),0) as "CPBQ_TTPT",'  
                + ' ROUND(SUM(T_KHAM),0) / ROUND(SUM(T_TONGCHI),0) as "CPBQ_TIENKHAM",'
                + ' ROUND(SUM(T_THUOC),0) / ROUND(SUM(T_TONGCHI),0) as "CPBQ_THUOC",'
                + ' CASE WHEN MA_CSKCB in (93001) THEN 93001'
                + ' WHEN MA_CSKCB in (93007) THEN 93007'
                + ' WHEN MA_CSKCB in (93002,93048,93049,93050,93051,93052,93053,93054,93055,93057,93080) THEN 93002'
                + ' WHEN MA_CSKCB in (93003,93019,93058,93059,93060,93061,93092,93094,93097,93104) THEN 93003'
                + ' WHEN MA_CSKCB in (93004,93035,93036,93037,93038,93039,93040,93041,93042,93043,93044,93045,93046,93047,93089,93090) THEN 93004'
                + ' WHEN MA_CSKCB in (93005,93026,93027,93028,93029,93030,93031,93032,93033,93087) THEN 93005'
                + ' WHEN MA_CSKCB in (93006,93018,93020,93022,93023,93024,93025,93073,93083,93084,93086) THEN 93006'
                + ' WHEN MA_CSKCB in (93109,93009,93010,93011,93012,93013,93014,93015,93017,93082) THEN 93109'
                + ' WHEN MA_CSKCB in (93016,93067,93068,93069,93070,93071,93072) THEN 93016'
                + ' WHEN MA_CSKCB in (93078,93062,93063,93064,93065,93066,93095,93096,93098) THEN 93078'
                + ' WHEN MA_CSKCB in (93008) THEN 93008'
                + ' WHEN MA_CSKCB in (93100) THEN 93100'
                + ' WHEN MA_CSKCB in (93102) THEN 93102'
                + ' WHEN MA_CSKCB in (93103) THEN 93103'
                + ' WHEN MA_CSKCB in (93105) THEN 93105'
                + ' WHEN MA_CSKCB in (93106) THEN 93106'
                + ' ELSE 93107 END As "MA_CHA"'
                + ' from bhyt7980a' 
                + ' WHERE KY_QT BETWEEN 202101 and 202108'
                + ' GROUP BY MA_CSKCB,MA_LOAI_KCB')

In [5]:
# chi phí phát sinh tại 1 cskcb
CURRENT= pd.read_sql_query(CHIPHITAICSKCB, con)
#CURRENT

In [6]:
# Dữ liệu tại năm hiện tại cần phân tích
con_before = sqlite3.connect(r'D:\DATACSDL\CSDL\2020\93_20210110_202001_202012_bao_cao_bhyt7980a.db')

In [7]:
CHIPHITAICSKCB_BEFORE = (r'SELECT MA_CSKCB,MA_LOAI_KCB,COUNT(MA_THE) AS "SO_LUOT",ROUND(SUM(T_TONGCHI),0) AS "TONGCHI",'
                + ' ROUND(SUM(T_KHAM),0) AS "T_KHAM",ROUND(SUM(T_TTPT),0) as "T_TTPT",ROUND(SUM(T_THUOC),0) as "T_THUOC",'
                + ' ROUND(SUM(T_TONGCHI),0) / COUNT(MA_THE) as "CPBQ_KCB",'
                + ' ROUND(SUM(T_TTPT),0) / ROUND(SUM(T_TONGCHI),0) as "CPBQ_TTPT",'  
                + ' ROUND(SUM(T_KHAM),0) / ROUND(SUM(T_TONGCHI),0) as "CPBQ_TIENKHAM",'
                + ' ROUND(SUM(T_THUOC),0) / ROUND(SUM(T_TONGCHI),0) as "CPBQ_THUOC",'
                + ' CASE WHEN MA_CSKCB in (93001) THEN 93001'
                + ' WHEN MA_CSKCB in (93007) THEN 93007'
                + ' WHEN MA_CSKCB in (93002,93048,93049,93050,93051,93052,93053,93054,93055,93057,93080) THEN 93002'
                + ' WHEN MA_CSKCB in (93003,93019,93058,93059,93060,93061,93092,93094,93097,93104) THEN 93003'
                + ' WHEN MA_CSKCB in (93004,93035,93036,93037,93038,93039,93040,93041,93042,93043,93044,93045,93046,93047,93089,93090) THEN 93004'
                + ' WHEN MA_CSKCB in (93005,93026,93027,93028,93029,93030,93031,93032,93033,93087) THEN 93005'
                + ' WHEN MA_CSKCB in (93006,93018,93020,93022,93023,93024,93025,93073,93083,93084,93086) THEN 93006'
                + ' WHEN MA_CSKCB in (93109,93009,93010,93011,93012,93013,93014,93015,93017,93082) THEN 93109'
                + ' WHEN MA_CSKCB in (93016,93067,93068,93069,93070,93071,93072) THEN 93016'
                + ' WHEN MA_CSKCB in (93078,93062,93063,93064,93065,93066,93095,93096,93098) THEN 93078'
                + ' WHEN MA_CSKCB in (93008) THEN 93008'
                + ' WHEN MA_CSKCB in (93100) THEN 93100'
                + ' WHEN MA_CSKCB in (93102) THEN 93102'
                + ' WHEN MA_CSKCB in (93103) THEN 93103'
                + ' WHEN MA_CSKCB in (93105) THEN 93105'
                + ' WHEN MA_CSKCB in (93106) THEN 93106'
                + ' ELSE 93107 END As "MA_CHA"'
                + ' from bhyt7980a' 
                + ' WHERE KY_QT BETWEEN 202001 and 202008'
                + ' GROUP BY MA_CSKCB,MA_LOAI_KCB')

In [8]:
# chi phí phát sinh tại 1 cskcb
BEFORE= pd.read_sql_query(CHIPHITAICSKCB_BEFORE, con_before)
#BEFORE

In [9]:
result = pd.merge(BEFORE, CURRENT,  how='left', left_on=['MA_CHA','MA_CSKCB','MA_LOAI_KCB'], right_on = ['MA_CHA','MA_CSKCB','MA_LOAI_KCB'], suffixes=('_KYTRUOC', '_KYHIENTAI'))
result = result.replace(np.nan, 0)
#result.info()

In [10]:
result["TANGGIAM_CPBQ_KCB"] = (result["CPBQ_KCB_KYHIENTAI"] / result["CPBQ_KCB_KYTRUOC"]) - 1
result["TANGGIAM_CPBQ_TTPT"] = (result["CPBQ_TTPT_KYHIENTAI"] - result["CPBQ_TTPT_KYTRUOC"])
result["TANGGIAM_CPBQ_TIENKHAM"] = (result["CPBQ_TIENKHAM_KYHIENTAI"] - result["CPBQ_TIENKHAM_KYTRUOC"])
result["TANGGIAM_CPBQ_THUOC"] = (result["CPBQ_THUOC_KYHIENTAI"] - result["CPBQ_THUOC_KYTRUOC"])

In [11]:
#result

,MA_CSKCB,MA_LOAI_KCB,SO_LUOT_KYTRUOC,TONGCHI_KYTRUOC,T_KHAM_KYTRUOC,T_TTPT_KYTRUOC,T_THUOC_KYTRUOC,CPBQ_KCB_KYTRUOC,CPBQ_TTPT_KYTRUOC,CPBQ_TIENKHAM_KYTRUOC,...,T_TTPT_KYHIENTAI,T_THUOC_KYHIENTAI,CPBQ_KCB_KYHIENTAI,CPBQ_TTPT_KYHIENTAI,CPBQ_TIENKHAM_KYHIENTAI,CPBQ_THUOC_KYHIENTAI,TANGGIAM_CPBQ_KCB,TANGGIAM_CPBQ_TTPT,TANGGIAM_CPBQ_TIENKHAM,TANGGIAM_CPBQ_THUOC
0,93001,1,31504,5.482122e+09,1.112359e+09,2.968133e+08,3.517142e+09,1.740135e+05,0.054142,0.202907,...,3.431024e+08,5.940836e+09,2.070067e+05,0.039629,0.171921,0.686179,0.189601,-0.014513,-0.030986,0.044613
1,93001,2,667,5.134425e+09,3.450000e+04,4.131080e+09,9.033949e+08,7.697788e+06,0.804585,0.000007,...,5.078504e+09,5.540556e+08,6.699439e+06,0.883507,0.000000,0.096389,-0.129693,0.078922,-0.000007,-0.079560
2,93001,3,14653,5.038324e+10,2.494522e+08,1.342477e+10,8.931743e+09,3.438425e+06,0.266453,0.004951,...,1.025577e+10,1.182332e+10,3.961988e+06,0.203806,0.006866,0.234957,0.152268,-0.062647,0.001914,0.057681
3,93002,1,54101,5.445354e+09,1.649946e+09,1.290441e+08,3.025812e+09,1.006516e+05,0.023698,0.303001,...,1.496501e+08,3.609144e+09,1.168931e+05,0.025349,0.260857,0.611350,0.161363,0.001651,-0.042144,0.055681
4,93002,2,280,1.765032e+08,8.479000e+06,1.331520e+08,3.464424e+07,6.303687e+05,0.754388,0.048039,...,2.086960e+08,4.817514e+07,9.811230e+05,0.784913,0.030513,0.181188,0.556427,0.030524,-0.017526,-0.015093
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
117,93103,3,553,7.071087e+08,8.662000e+06,2.167470e+08,5.470160e+07,1.278678e+06,0.306526,0.012250,...,1.465904e+08,4.376923e+07,1.328399e+06,0.298246,0.008812,0.089051,0.038885,-0.008279,-0.003438,0.011691
118,93104,1,3679,2.075081e+08,1.011725e+08,2.637250e+06,1.036983e+08,5.640339e+04,0.012709,0.487559,...,2.489620e+06,8.947364e+07,6.121087e+04,0.014909,0.449267,0.535824,0.085234,0.002200,-0.038293,0.036092
119,93105,1,2519,6.973277e+08,6.927250e+07,0.000000e+00,6.280552e+08,2.768272e+05,0.000000,0.099340,...,0.000000e+00,6.043602e+08,4.303241e+05,0.000000,0.061210,0.938790,0.554486,0.000000,-0.038130,0.038130
120,93106,1,4962,6.324013e+08,1.477740e+08,1.911000e+07,2.019641e+08,1.274489e+05,0.030218,0.233671,...,1.146600e+07,1.092297e+08,1.193019e+05,0.027906,0.230441,0.265846,-0.063924,-0.002312,-0.003231,-0.053515
121,93107,1,430,4.373855e+07,1.171500e+07,0.000000e+00,6.890448e+06,1.017176e+05,0.000000,0.267842,...,0.000000e+00,9.542089e+07,8.294579e+04,0.000000,0.331696,0.133845,-0.184548,0.000000,0.063855,-0.023692

In [14]:
total_result = result[["MA_CHA","MA_CSKCB","MA_LOAI_KCB","SO_LUOT_KYTRUOC","SO_LUOT_KYHIENTAI","T_KHAM_KYTRUOC","T_KHAM_KYHIENTAI","T_TTPT_KYTRUOC","T_TTPT_KYHIENTAI","T_THUOC_KYTRUOC","T_THUOC_KYHIENTAI","TONGCHI_KYTRUOC","TONGCHI_KYHIENTAI","CPBQ_KCB_KYTRUOC","CPBQ_KCB_KYHIENTAI","TANGGIAM_CPBQ_KCB","CPBQ_TTPT_KYTRUOC","CPBQ_TTPT_KYHIENTAI","TANGGIAM_CPBQ_TTPT","CPBQ_TIENKHAM_KYTRUOC","CPBQ_TIENKHAM_KYHIENTAI","TANGGIAM_CPBQ_TIENKHAM","CPBQ_THUOC_KYTRUOC","CPBQ_THUOC_KYHIENTAI","TANGGIAM_CPBQ_THUOC"]].copy()

In [15]:
total_result.to_excel(r'D:\SOLIEU\SOLIEUPHANTICH\SOSANH\BAOCAOGIAMSATCHIPHITRONGTINH.xlsx')

# Phân tích chi phí đa tuyến đi

In [2]:
# Dữ liệu tại năm hiện tại cần phân tích
con = sqlite3.connect(r'D:\DATACSDL\CSDL\2021\93_20210912_202101_202108_bao_cao_bhyt7980a_dtdi.db')

In [3]:
CHIPHITAICSKCB = (r'SELECT MA_DKBD,COUNT(MA_THE) AS "SO_LUOT",ROUND(SUM(T_BHTT),0) AS "T_BHTT",'
                + ' CASE WHEN SUBSTR(MA_DKBD,1,2) != "93" THEN "ĐĂNG KÝ NGOÀI TỈNH"'               
                + ' ELSE "THẺ TRONG TỈNH" END As "MA_CHA"'
                + ' from bhyt7980a_dtdi' 
                + ' WHERE KY_QT BETWEEN 202101 and 202108'
                + ' GROUP BY MA_CHA,MA_DKBD')

In [4]:
# Đọc dữ liệu SQL từ kỳ hiện tại
CURRENT= pd.read_sql_query(CHIPHITAICSKCB, con)
#CURRENT

In [5]:
# Dữ liệu SQL từ kỳ trước đó
con_before = sqlite3.connect(r'D:\DATACSDL\CSDL\2020\93_20210110_202001_202012_bao_cao_bhyt7980a_dtdi.db')

In [6]:
CHIPHITAICSKCB = (r'SELECT MA_DKBD,COUNT(MA_THE) AS "SO_LUOT",ROUND(SUM(T_BHTT),0) AS "T_BHTT",'
                + ' CASE WHEN SUBSTR(MA_DKBD,1,2) != "93" THEN "ĐĂNG KÝ NGOÀI TỈNH"'               
                + ' ELSE "THẺ TRONG TỈNH" END As "MA_CHA"'
                + ' from bhyt7980a_dtdi' 
                + ' WHERE KY_QT BETWEEN 202001 and 202008'
                + ' GROUP BY MA_CHA,MA_DKBD')

In [7]:
# chi phí phát sinh kỳ trước đó
BEFORE= pd.read_sql_query(CHIPHITAICSKCB, con_before)
#BEFORE

In [8]:
# Xử lý kết nối kỳ trước và kỳ hiện tại vào 1 Frame
result = pd.merge(BEFORE, CURRENT,  how='left', left_on=['MA_CHA','MA_DKBD'], right_on = ['MA_CHA','MA_DKBD'], suffixes=('_KYTRUOC', '_KYHIENTAI'))

In [11]:
result["TANGGIAM_SOLUOT_KCB"] = (result["SO_LUOT_KYHIENTAI"] / result["SO_LUOT_KYTRUOC"]) - 1
result["TANGGIAM_CHIPHI_KCB"] = (result["T_BHTT_KYTRUOC"] / result["T_BHTT_KYHIENTAI"]) - 1

In [14]:
total_result = result[["MA_CHA","MA_DKBD","SO_LUOT_KYTRUOC","SO_LUOT_KYHIENTAI","TANGGIAM_SOLUOT_KCB","T_BHTT_KYTRUOC","T_BHTT_KYHIENTAI","TANGGIAM_CHIPHI_KCB"]].copy()

In [15]:
total_result.to_excel(r'D:\SOLIEU\SOLIEUPHANTICH\SOSANH\BAOGIAMGIAMSATDATUYENDI.xlsx')

# Tỷ lệ gia tăng chỉ định điều trị nội trú

In [14]:
NOI_TRU_BEFORE = BEFORE[(BEFORE['MA_LOAI_KCB'] == 3)] # Tổng số lượt nội trú KCB trong CSCKB kỳ trước
NOI_BEFORE= NOI_TRU_BEFORE.groupby(["MA_CSKCB"]).agg({'SO_LUOT':'sum'}) # Gom nhóm chi phí nội trú của các CSCKB kỳ trước
TONG_BEFORE = BEFORE.groupby(["MA_CSKCB"]).agg({'SO_LUOT':'sum'}) # gom nhóm chi phí KCB của từng CSCKB kỳ trước 

NOI_TRU_CURRENT = CURRENT[(CURRENT['MA_LOAI_KCB'] == 3)] # Lưu các chi phí nội trú kỳ hiện tại
NOI_CURRENT= NOI_TRU_CURRENT.groupby(["MA_CSKCB"]).agg({'SO_LUOT':'sum'}) # Tổng số lượt nội trú KCB trong các CSCKB kỳ hiện tại
TONG_CURRENT = CURRENT.groupby(["MA_CSKCB"]).agg({'SO_LUOT':'sum'}) # Tổng số lượt KCB của từng CSKCB kỳ hiện tại

# xử lý nối chi phí nội trú với tổng chi phí của kỳ trước
RESULT_BEFORE = pd.merge(NOI_BEFORE, TONG_BEFORE,  how='left', left_on=['MA_CSKCB'], right_on = ['MA_CSKCB'],suffixes=('_BEFORE', '_TONGLUOT')) 
# xử lý nối chi phí nội trú với tổng chi phí của kỳ hiện tại
RESULT_CURRENT = pd.merge(NOI_CURRENT, TONG_CURRENT,  how='left', left_on=['MA_CSKCB'], right_on = ['MA_CSKCB'],suffixes=('_CURRENT', '_TONGLUOT'))
# tính tỷ lệ tăng giảm của kỳ hiện tại
RESULT_CURRENT["TYLE_CHIDINHNOITRU_KYHIENTAI"] = (RESULT_CURRENT["SO_LUOT_CURRENT"] / RESULT_CURRENT["SO_LUOT_TONGLUOT"])
# tính tỷ lệ tăng giảm của kỳ trước
RESULT_BEFORE["TYLE_CHIDINHNOITRU_KYTRUOC"] = (RESULT_BEFORE["SO_LUOT_BEFORE"] / RESULT_BEFORE["SO_LUOT_TONGLUOT"])

In [21]:
# xử lý nối kỳ trước và kỳ hiện tại vào 1 file
result = pd.merge(RESULT_BEFORE, RESULT_CURRENT,  how='left', left_on=['MA_CSKCB'], right_on = ['MA_CSKCB'], suffixes=('_KYTRUOC', '_KYHIENTAI'))

In [25]:
# tính chi phí tăng giảm chỉ định nội trú
result["TANGGIAM_CHIDINH_DTRINOITRU"] = (result["TYLE_CHIDINHNOITRU_KYHIENTAI"] - result["TYLE_CHIDINHNOITRU_KYTRUOC"])

In [26]:
# lọc các trường cần thiết khi xuất file ra Excel
total_result = result[["SO_LUOT_BEFORE","SO_LUOT_CURRENT","SO_LUOT_TONGLUOT_KYTRUOC","SO_LUOT_TONGLUOT_KYHIENTAI","TYLE_CHIDINHNOITRU_KYHIENTAI","TYLE_CHIDINHNOITRU_KYTRUOC","TANGGIAM_CHIDINH_DTRINOITRU"]].copy()
total_result.to_excel(r'D:\SOLIEU\SOLIEUPHANTICH\SOSANH\BAOGIAMGIAMSATCHIDINHNOITRU.xlsx')